Drop support for rand_core < 0.6
rust-random/seeder pull request #10
Opened 2024-07-30 18:23 UTC by sunshowers

This works around a Cargo issue where unrelated updates can cause the `rand_core` dependency to "snap back" to older versions.

Fixes #9.

2024-07-31 08:50 UTC, dhardy requested changes
Set the `version` to 0.3 and change the "Unreleased" title in the changelog please, then I can just publish (assuming tests pass).

Looks fine otherwise.

2024-07-31 19:38 UTC, sunshowers commented
Oh sorry, push failed. Just a sec

2024-07-31 19:39 UTC, sunshowers commented
All right, pushed the version bump. Thanks!

2024-08-01 08:50 UTC, dhardy approved these changes

2024-08-01 17:54 UTC, sunshowers commented
Thanks — looks like the CI issue is unrelated (maybe the target got renamed?)

2024-08-01 19:57 UTC, dhardy commented
Yes, that's unrelated. It needs fixing but there's no real reason it should stop this PR.

2024-08-01 19:57 UTC, merged